services:
  zeroscope-api:
    build: .
    container_name: zeroscope-api
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:32  # Otimização de memória
      - CUDA_LAUNCH_BLOCKING=1  # Para melhores mensagens de erro
      - TF_FORCE_UNIFIED_MEMORY=1
      - XLA_PYTHON_CLIENT_MEM_FRACTION=0.8
      - OUTPUT_VIDEOS_DIR=/app/output_videos  # Nova variável de ambiente
    ports:
      - "8000:8000"
    shm_size: '2gb'
    volumes:
      - ./model_cache:/root/.cache/huggingface
      - ./output_videos:/app/output_videos       # Volume para os vídeos gerados
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped